export type Book = {
  bookId: number;
  bookName: string;
  author: string;
  image: string;
  review: string;
  totalPages: number;
  rating: number;
  category: string;
  tags: string[];
  publisher: string;
  yearOfPublishing: number;
  source?: "curated" | "openlibrary";
  openLibraryKey?: string;
  workId?: string;
  iaId?: string;
  readOnlineUrl?: string;
  hasFulltext?: boolean;
  isCustom?: boolean;
};
